const Images = {
  banner1: require('../assets/images/banner1.png'),
  menu: require('../assets/menu.png'),
  attendance: require('../assets/images/Attendance.png'),
  money: require('../assets/images/money.png'),
  library: require('../assets/images/library.png'),
  exam: require('../assets/images/exam.png'),
  examRedirect: require('../assets/images/exam-redirect.png'),
  dashboardAttendance: require('../assets/images/d-attendance.png'),
  dashboardtimeTable: require('../assets/images/d-calendar.png'),
  dashboardlibrary: require('../assets/images/d-book.png'),
  dashboardexam: require('../assets/images/d-exam.png'),
  dashboardnoticeboard: require('../assets/images/d-noticeboard.png'),
  dashboardfeeAnalysis: require('../assets/images/d-fee.png'),
  dashboardfeeReciept: require('../assets/images/d-reciept.png'),
  dashboardfeedback: require('../assets/images/d-feedback.png'),
  schoolCover: require('../assets/images/school.png'),
  profile: require('../assets/images/profile.png'),
  collegeDetails: require('../assets/images/p-collegedetails.png'),
  proffessorDetails: require('../assets/images/p-proffesors.png'),
  writetoDeatils: require('../assets/images/p-writeto.png'),
  inboxProfile1: require('../assets/images/inbox-profile.png'),
  inboxProfile2: require('../assets/images/inbox-profile2.png'),
  inboxProfile3: require('../assets/images/inbox-profile3.png'),
  inboxTick: require('../assets/images/inbox-tick.png'),
};
export default Images;
